const fs=require('fs'),vm=require('vm'),assert=require('assert/strict'),path=require('path');
const source=fs.readFileSync(path.join(__dirname,'../weather.js'),'utf8');
const uiSource=fs.readFileSync(path.join(__dirname,'../weather-ui.js'),'utf8');
const event={activityType:'outdoor',date:'2026-10-06',startTime:'10:30',endTime:'12:30',weatherLocation:{name:'Bandung',latitude:-6.9,longitude:107.6}};
const start=new Date(event.date+'T00:00:00').getTime();
function data(p=10,code=0){return {timezone:'Asia/Jakarta',hourly:{time:Array.from({length:48},(_,i)=>(start+i*3600000)/1000),precipitation_probability:Array(48).fill(p),precipitation:Array(48).fill(0),weather_code:Array(48).fill(code)}};}
function engine(options={}){const values=new Map();let online=true,now=start,calls=0,fail=false;
 const ctx={window:{},navigator:{onLine:true},localStorage:{getItem:k=>values.get(k)||null,setItem:(k,v)=>values.set(k,v)},Date,Intl,URL,URLSearchParams,AbortController,setTimeout,clearTimeout};vm.createContext(ctx);vm.runInContext(source,ctx);
 const api=ctx.window.FahmiWeather.create({request:options.request || (async url=>{calls++;if(fail)throw Error('network failed');return {ok:true,json:async()=>url.includes('geocoding')?{results:[{name:'Bandung',latitude:-6.9,longitude:107.6},{name:'Bad',latitude:200,longitude:0}]}:data()}}),storage:ctx.localStorage,clock:()=>now,online:()=>online});
 return {ctx,api,analyze:ctx.window.FahmiWeather.analyze,values,get calls(){return calls},set online(v){online=v},set now(v){now=v},set fail(v){fail=v}};
}
let passed=0;async function test(name,fn){await fn();passed++;console.log('PASS',name)}
function uiFixture(options={}){
 const base=engine(),els=new Map(),timers=new Map();let next=0,state={settings:{weatherThreshold:60}},form={...event,title:'Lari'},list=[],geoError,geoSuccess,resolveCheck,delayed=false,notifies=0,answer={state:'rain',reason:'Kemungkinan 80%',probability:80,amount:1,condition:'Hujan',zone:'Asia/Jakarta',localTime:'06 Okt 10:30',at:Date.now(),signature:'test'},done=[];
 const el=id=>{if(!els.has(id)){const classes=new Set(),attributes={};els.set(id,{value:'',textContent:'',innerHTML:'',open:false,disabled:false,setAttribute(k,v){attributes[k]=v},getAttribute:k=>attributes[k],classList:{toggle(k,v){v?classes.add(k):classes.delete(k)},contains:k=>classes.has(k)},addEventListener(){},querySelectorAll(){return []},showModal(){this.open=true},close(){this.open=false},focus(){}})}return els.get(id)};
 const api={check:async()=>delayed?new Promise(r=>resolveCheck=r):answer,search:async()=>[{name:'Bandung',latitude:-6.9,longitude:107.6}]};
 const ctx={window:{FahmiWeather:{...base.ctx.window.FahmiWeather,create:()=>api},addEventListener(){}},document:{hidden:false,getElementById:el,addEventListener(){}},navigator:{onLine:true,geolocation:{getCurrentPosition(ok,fail){geoSuccess=ok;geoError=fail}},serviceWorker:{getRegistration:async()=>({showNotification:async()=>{notifies++}})}},localStorage:base.ctx.localStorage,Notification:{permission:'granted'},Date,Intl,setTimeout(fn){const id=++next;timers.set(id,fn);return id},clearTimeout:id=>timers.delete(id),confirm:()=>true};
 let geoCalls=0,permissionCalls=0;const originalGet=ctx.navigator.geolocation.getCurrentPosition;
 ctx.navigator.geolocation.getCurrentPosition=(...args)=>{geoCalls++;originalGet(...args)};
 if(options.permission!==undefined)ctx.navigator.permissions={query:async()=>{permissionCalls++;if(options.permission==='unsupported')throw Error('not supported');return {state:options.permission}}};
 if(options.permissionPromise)ctx.navigator.permissions={query:()=>{permissionCalls++;return options.permissionPromise}};
 ctx.window.Notification=ctx.Notification;vm.createContext(ctx);vm.runInContext(uiSource,ctx);let ui;
 ui=ctx.window.FahmiWeatherUI.create({getState:()=>state,getForm:()=>({...form,...ui.fields()}),getOccurrences:()=>list,getConflicts:()=>[],onRefresh(){},escapeHtml:x=>String(x??''),toast(){}});
 el('eventDialog').open=true;ui.open({...form,status:'scheduled'});
 return {ui,el,ctx,done,get geoCalls(){return geoCalls},get permissionCalls(){return permissionCalls},get form(){return form},set form(v){form=v},set list(v){list=v},set delayed(v){delayed=v},set answer(v){answer=v},get notifies(){return notifies},resolve:()=>resolveCheck(answer),deny:()=>geoError({code:1}),geo:()=>geoSuccess({coords:{latitude:-6.9,longitude:107.6}}),save:(e=form)=>ui.gate({...e,...ui.fields()},(d,c)=>done.push({data:d,cancel:c})),async flush(){const fn=[...timers.values()].at(-1);timers.clear();if(fn)await fn()}};
}
(async()=>{
 await test('Hourly interval covers both partial ends and full duration',()=>{const f=engine(),d=data();d.hourly.precipitation_probability[13]=80;const r=f.analyze(d,event);assert.equal(r.state,'rain');assert.equal(r.probability,80);d.hourly.precipitation_probability[13]=10;d.hourly.precipitation_probability[10]=95;d.hourly.weather_code[10]=0;assert.equal(f.analyze(d,event).state,'low')});
 await test('Rain/storm fallback, null probability, unknown/incomplete data and threshold',()=>{const f=engine();assert.equal(f.analyze(data(null,95),event).state,'rain');assert.equal(f.analyze(data(null,0),event).state,'low');assert.equal(f.analyze(data(null,null),event).state,'unavailable');assert.equal(f.analyze(data(null,34),event).state,'unavailable');assert.equal(f.analyze(data(60),event,60).state,'rain');assert.equal(f.analyze(data(60),event,70).state,'low');const d=data();d.hourly.time.splice(12,1);assert.equal(f.analyze(d,event).state,'unavailable')});
 await test('Outside range is never called safe; location time zone uses actual instant',()=>{const f=engine();assert.equal(f.analyze(data(),{...event,date:'2026-12-01'}).state,'unavailable');const r=f.analyze({...data(),timezone:'Asia/Makassar'},event);assert.equal(r.zone,'Asia/Makassar');assert(r.localTime.includes(new Intl.DateTimeFormat('id-ID',{timeZone:'Asia/Makassar',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(new Date(event.date+'T10:30:00'))))});
 await test('Indoor and distant schedules make no network request',async()=>{const f=engine();assert.equal((await f.api.check({...event,activityType:'indoor'})).state,'indoor');assert.equal((await f.api.check({...event,date:'2026-12-01'})).state,'unavailable');assert.equal(f.calls,0)});
 await test('Cache survives requests, offline stale is marked and failure never marks safe',async()=>{const f=engine();await f.api.check(event);await f.api.check(event);assert.equal(f.calls,1);f.now=start+31*60000;f.online=false;const old=await f.api.check(event);assert(old.stale);const g=engine();g.online=false;assert.equal((await g.api.check(event)).state,'unavailable');f.online=true;f.fail=true;assert((await f.api.check(event)).stale)});
 await test('City search validates coordinates and denied/invalid locations remain unavailable',async()=>{const f=engine();assert.equal((await f.api.search('Bandung')).length,1);assert.equal((await f.api.check({...event,weatherLocation:null})).state,'unavailable');assert.equal(f.ctx.window.FahmiWeather.validLocation({name:'Bad',latitude:91,longitude:0}),false)});
 await test('Concurrent checks share one forecast request',async()=>{const f=engine();await Promise.all([f.api.check(event),f.api.check({...event,startTime:'11:00'})]);assert.equal(f.calls,1)});
 await test('Rain review waits for user; keep/cancel preserve data and change does not save',async()=>{const f=uiFixture();await f.save();assert.equal(f.done.length,0);assert(f.el('weatherRiskDialog').open);f.el('weatherChangeBtn').onclick();assert.equal(f.done.length,0);await f.save();f.el('weatherKeepBtn').onclick();assert.equal(f.done[0].data.weatherAccepted,'test');assert.equal(f.done[0].data.title,'Lari');await f.save();f.el('weatherCancelBtn').onclick();assert.equal(f.done[1].cancel,true)});
 await test('Old responses and closed forms cannot render or save stale data',async()=>{const f=uiFixture();f.delayed=true;const pending=f.save();f.form={...f.form,startTime:'11:00'};f.ui.changed();f.resolve();await pending;assert.equal(f.done.length,0);assert(!f.el('weatherRiskDialog').open)});
 await test('Unavailable forecast permits saving, indoor does not warn, geolocation denial keeps manual search',async()=>{const f=uiFixture();f.answer={state:'unavailable',reason:'Offline'};await f.save();assert.equal(f.done.length,1);f.el('eventActivityType').value='indoor';await f.save();assert.equal(f.done.length,2);f.el('eventActivityType').value='outdoor';f.el('weatherMyLocationBtn').onclick();await f.el('weatherLocateBtn').onclick();f.deny();assert(f.el('weatherSelectedLocation').textContent.includes('Pilih lokasi lain'));assert.equal(typeof f.el('weatherSearchBtn').onclick,'function')});
 await test('Upcoming recurring occurrence risk notifies once; done/cancelled ignored',async()=>{const f=uiFixture();const o={...event,eventId:'series',title:'Lari',status:'scheduled',startDateTime:new Date(Date.now()+3600000),endDateTime:new Date(Date.now()+7200000)};f.list=[o,{...o,eventId:'done',status:'done'},{...o,eventId:'cancelled',status:'cancelled'}];await f.ui.refresh(true);await f.ui.refresh(true);assert.equal(f.notifies,1);assert(f.ui.badge(o).includes('Risiko hujan'));assert(!f.ui.badge({...o,status:'done'}).includes('Risiko hujan'));});
 const settle=async()=>{for(let i=0;i<4;i++)await Promise.resolve()};
 const outdoorNew=async f=>{f.ui.open();f.el('eventActivityType').value='outdoor';f.el('eventActivityType').onchange();await settle()};
 await test('New Outdoor defaults to my location; granted permission uses one snapshot automatically',async()=>{const f=uiFixture({permission:'granted'});await outdoorNew(f);assert.equal(f.geoCalls,1);assert.equal(f.el('weatherMyLocationBtn').getAttribute('aria-pressed'),'true');f.geo();assert.equal(f.ui.fields().weatherLocation.name,'Lokasi Saya');assert(f.el('weatherLocationChoice').classList.contains('hidden'));f.ui.changed();assert.equal(f.geoCalls,1)});
 await test('Prompt, unsupported or missing permission API waits for explicit button',async()=>{for(const permission of ['prompt','unsupported',undefined]){const f=uiFixture({permission});await outdoorNew(f);assert.equal(f.geoCalls,0);assert(f.el('weatherManualFields').classList.contains('hidden'));await f.el('weatherLocateBtn').onclick();assert.equal(f.geoCalls,1);f.geo();assert.equal(f.ui.fields().weatherLocation.latitude,-6.9)}});
 await test('Denied permission does not request again and opens manual location option',async()=>{const f=uiFixture({permission:'denied'});await outdoorNew(f);assert.equal(f.geoCalls,0);assert(!f.el('weatherManualFields').classList.contains('hidden'));assert.equal(f.el('weatherSelectedLocation').textContent,'Lokasi tidak tersedia. Pilih lokasi lain.');await f.el('weatherLocateBtn').onclick();assert.equal(f.geoCalls,0)});
 await test('GPS failure falls back manually; Indoor never queries or acquires location',async()=>{const f=uiFixture({permission:'granted'});f.ui.open();f.ui.changed();await settle();assert.equal(f.geoCalls,0);assert.equal(f.permissionCalls,0);await outdoorNew(f);f.deny();assert(!f.el('weatherManualFields').classList.contains('hidden'))});
 await test('Saved device/manual locations remain fixed when editing and repeated forms reopen',async()=>{for(const name of ['Lokasi Saya','Lokasi perangkat','Bandung']){const f=uiFixture({permission:'granted'});f.ui.open({...event,weatherLocation:{name,latitude:-8,longitude:115},recurrence:{type:'daily'}});await settle();assert.equal(f.geoCalls,0);assert.equal(f.permissionCalls,0);assert.equal(f.ui.fields().weatherLocation.latitude,-8);assert(f.el('weatherLocationChoice').classList.contains('hidden'))}});
 await test('Late GPS or permission response cannot overwrite manual choice, Indoor, or reopened form',async()=>{const f=uiFixture({permission:'granted'});await outdoorNew(f);f.el('weatherOtherLocationBtn').onclick();f.geo();assert.equal(f.ui.fields().weatherLocation,null);assert.equal(f.el('weatherOtherLocationBtn').getAttribute('aria-pressed'),'true');const g=uiFixture({permission:'granted'});await outdoorNew(g);g.ui.open({...event});g.geo();assert.equal(g.ui.fields().weatherLocation.name,'Bandung');const h=uiFixture({permission:'granted'});await outdoorNew(h);h.el('eventActivityType').value='indoor';h.el('eventActivityType').onchange();h.geo();assert.equal(h.ui.fields().weatherLocation,null)});
 await test('Compact weather hides technical details by default and limits alternatives to two',async()=>{const f=uiFixture();f.answer={state:'rain',reason:'Model explanation',probability:80,amount:1,condition:'Hujan',zone:'Asia/Jakarta',localTime:'10:30',at:Date.now(),signature:'x',data:data()};await f.save();const html=f.el('weatherRiskText').innerHTML;assert(html.includes('Lari'));assert(html.includes('Pertimbangkan mengganti waktu kegiatan.'));assert(html.includes('<details><summary>Lihat Detail'));assert(!html.includes('<details open'));assert(html.indexOf('Model explanation')>html.indexOf('<details>'));assert.equal((html.match(/data-weather-alternative=/g)||[]).length,2)});
 await test('Delayed permission result is ignored after choosing manual location',async()=>{let resolve;const promise=new Promise(r=>resolve=r),f=uiFixture({permissionPromise:promise});await outdoorNew(f);f.el('weatherOtherLocationBtn').onclick();resolve({state:'granted'});await settle();assert.equal(f.geoCalls,0);assert.equal(f.el('weatherOtherLocationBtn').getAttribute('aria-pressed'),'true')});
 console.log(`${passed} weather tests passed.`);
})().catch(e=>{console.error(e);process.exitCode=1});
